Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class Comment
    {
        [Key]
        [Column(Order = 1)]
        public int CommentId { get; set; }
        public int BillId { get; set; }
        public string UserId { get; set; }
        [StringLength(1000, ErrorMessage = "Bình luận chỉ được tối đa 1000 ký tự!")]
        [Required]
        public string UserComment { get; set; }
        [Required]
        public DateTime CommentDate { get; set; }
        public bool Status { get; set; }
        public ApplicationUser User { get; set; }

        public virtual Bill Bill { get; set; }
    }
}

Controllers/CommentsController.cs
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace MicroWaveFood.Controllers
{
    [Authorize(Roles = "admin, manager")]
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        // GET: Comments
        public ActionResult Index()
        {
            var list = db.Products.Include("Bills.Comment").Where(a => a.status == true ).ToList();
            return View(list);
        }

        public ActionResult Detail(int Id)
        {
            var product = db.Products.Include("Bills.Comment.User").Where(a => a.status == true).FirstOrDefault(a => a.ProductId == Id);
            if (product == null)
            {
                ViewBag.Message = "Product not found!";
                return View("error");
            }
            return View(product);
        }

        public ActionResult Delete(int Id, string strUrl)
        {
            var comment = db.Comments.FirstOrDefault(a => a.CommentId == Id);
            if (comment != null)
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
            } 
            else
            {
                ViewBag.Messge = "Error when deleting comment";
                return View("error");
            }
            return Redirect(strUrl);
        }
    }
}

Views/Comments/Detail.cshtml
@model MicroWaveFood.Models.Product
@{
    ViewBag.Title = "Detail";
}

<h2>Product comments detail</h2>
<div class="container">
    <div class="history-wrapper">
        <div class="history-nav row shadow p-3 mb-5 bg-white rounded">
            <div class="col py-3 text-center">
                <div class="product-detail-history row col" style="flex-direction: column;">
                    <div class="product-image-history">
                        <img class="img-detail-history m-2" src="@Model.Image" style=" height: 200px; width: 200px;" />
                    </div>
                    <div class="product-info-history">
                        <div class="product-name-history m-2">
                            <a>@Model.ProductName</a>
                        </div>
                        <div class="product-name-history m-2">
                            <a>@Model.Price <span>đ</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="history-detail">
            @foreach (var item in Model.Bills)
            {
                if (item.Comment != null)
                {
                    <div class="shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                        <div class="row">
                            <div class="product-detail-history row col-10 ">
                                <div class="user-icon">
                                    <img src="~/Images/user-icon.jpg" style="width:60px; height: 60px; border-radius: 30px;"/>
                                </div>
                                <div class="product-info-history col">
                                    <div class="product-name-history m-2">
                                        <a>@item.Comment.User.Email</a>
                                    </div>
                                    <div class="product-name-history m-2">
                                        <a>@item.Comment.UserComment</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col" style="display: flex; align-items: flex-end; justify-content: flex-end;">
                                <button class="button-comment-order comment-click" data-product-id="@item.ProductId" data-link="@Url.Action("Delete", "Comments", new { id = item.Comment.CommentId, strURL = Request.Url.ToString() })">
                                    Delete this comment
                                </button>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('.comment-click').on("click", function (e) {
                bootbox.confirm("Delete this comment?", function (result) {
                    if (result == true) {
                        var value = $(e.target);
                        window.location = value.attr("data-link");
                    }
                    
                });
                

            });
        })
    </script>    
}

Views/Comments/Index.cshtml
@model IEnumerable<MicroWaveFood.Models.Product>
@{
    ViewBag.Title = "Index";
}

<h2>Comments</h2>
<div class="container">
    <div class="history-wrapper">
        <div class="history-nav row shadow p-3 mb-5 bg-white rounded">
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active">Tất cả</a>
            </div>
        </div>
        <div class="history-detail">
            @foreach (var item in Model)
            {
               
                <div class="shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                    <div class="row">
                        <div class="product-detail-history row col-10 ">
                            <div class="product-image-history">
                                <img class="img-detail-history m-2" src="@item.Image" />
                            </div>
                            <div class="product-info-history">
                                <div class="product-name-history m-2">
                                    <a>@item.ProductName</a>
                                </div>
                            </div>
                        </div>
                        <div class="col" style="display: flex; align-items: flex-end; justify-content: flex-end;">
                            <button class="button-comment-order comment-click" data-product-id="@item.ProductId">
                                @Html.ActionLink("Manage this product comments", "Detail", new { id = item.ProductId }, new { @class = "text-white" })
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@*@section scripts
    {
        <script>
            $(document).ready(function () {
                $('.comment-click').on("click", function (e) {
                    var productId = $(e.target);
                    $.get("/Comments/detail/", { productId = productId.attr("data-product-id") });
                });
            })
        </script>
    }*@