Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class Comment
    {
        [Key]
        [Column(Order = 1)]
        public int CommentId { get; set; }
        public int BillId { get; set; }
        public string UserId { get; set; }
        [StringLength(1000, ErrorMessage = "Bình luận chỉ được tối đa 1000 ký tự!")]
        [Required]
        public string UserComment { get; set; }
        [Required]
        public DateTime CommentDate { get; set; }
        public bool Status { get; set; }
        public ApplicationUser User { get; set; }

        public virtual Bill Bill { get; set; }
    }
}

Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class Order
    {
        [Key]
        [Column(Order = 1)]
        public int OrderId { get; set; }
        [Required]
        public DateTime OrderDate { get; set; }
        public long? Total { get; set; }
        public bool? IsDelivered { get; set; }
        public bool Status { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public virtual List<Bill> Bills { get; set; }
    }
}

Controllers/Api/OrderController.cs
using MicroWaveFood.Dtos;
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MicroWaveFood.Controllers.Api
{
    [Authorize(Roles = "admin")]
    public class OrderController : ApiController
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        [HttpPost]
        public IHttpActionResult OrderConfirm(OrderDto order)
        {
            if (order == null)
            {
                return BadRequest();
            }
            var confirmOrder = db.Orders.Find(order.OrderId);
            if (confirmOrder == null)
            {
                return BadRequest();
            }
            confirmOrder.IsDelivered = true;
            db.Entry(confirmOrder).State = EntityState.Modified;
            db.SaveChanges();
            return Ok();
        }
    }
}

Controllers/CommentsController.cs
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace MicroWaveFood.Controllers
{
    [Authorize(Roles = "admin, manager")]
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        // GET: Comments
        public ActionResult Index()
        {
            var list = db.Products.Include("Bills.Comment").Where(a => a.status == true ).ToList();
            return View(list);
        }

        public ActionResult Detail(int Id)
        {
            var product = db.Products.Include("Bills.Comment.User").Where(a => a.status == true).FirstOrDefault(a => a.ProductId == Id);
            if (product == null)
            {
                ViewBag.Message = "Product not found!";
                return View("error");
            }
            return View(product);
        }

        public ActionResult Delete(int Id, string strUrl)
        {
            var comment = db.Comments.FirstOrDefault(a => a.CommentId == Id);
            if (comment != null)
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
            } 
            else
            {
                ViewBag.Messge = "Error when deleting comment";
                return View("error");
            }
            return Redirect(strUrl);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNet.Identity;
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net.Mail;
using System.Net;

namespace MicroWaveFood.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public List<Cart> TakeCart()
        {
            //List<Cart> listCart = Session["Cart"] as List<Cart>;
            List<Cart> listCart = ListCart.Carts;
            if (listCart == null)
            {
                //if list cart doesn't exist, create one
                listCart = new List<Cart>();
                ListCart.Carts = listCart;
                //Session["Cart"] = listCart;
            }
            return listCart;
        }
        public int AmountSum()
        {
            int amount = 0;
            //List<Cart> list = Session["Cart"] as List<Cart>;
            List<Cart> list = ListCart.Carts;
            if (list != null)
            {
                amount = list.Sum(n => n.Amount);
            }
            return amount;
        }

        public long PriceSum()
        {
            long sum = 0;
            //List<Cart> list = Session["Cart"] as List<Cart>;
            List<Cart> list = ListCart.Carts;
            if (list != null)
            {
                sum = list.Sum(n => n.Total);
            }
            return sum;
        }

        //====================================================================
        // GET: Order
        public ActionResult Payment()
        {
            List<Cart> list = TakeCart();
            Order order = new Order();
            order.UserId = User.Identity.GetUserId();
            order.OrderDate = DateTime.Now;
            order.Status = true;
            order.IsDelivered = false;
            order.Total = PriceSum();
            db.Orders.Add(order);
            db.SaveChanges();

            string _body = "";
            foreach (Cart cart in list)
            {
                Product product = db.Products.Find(cart.ProductId);
                if (product == null)
                {
                    ViewBag.Title = "Error when creating Order";
                    ViewBag.Message = "Product not found!";
                    return View("Error");
                }
                Bill bill = new Bill();
                bill.OrderId = order.OrderId;
                bill.ProductId = product.ProductId;
                bill.Amount = cart.Amount;
                bill.Status = true;
                db.Bills.Add(bill);


                _body += "Tên sản phẩm: " + cart.ProductName.ToString();
                _body += " - Giá: " + cart.ProductPrice.ToString();
                _body += " - Số lượng: " + cart.Amount.ToString();
                _body += " - thành tiền: " + (cart.ProductPrice * cart.Amount).ToString();
                _body += "\n";
                db.SaveChanges();
            }

            _body += "\n Tổng tiền: " + order.Total.ToString();
            ViewBag.Title = "Thanh toán thành công! Chúng tôi sẽ giao hàng cho quí khách trong thời gian sớm nhất!";


            var user = db.Users.Find(User.Identity.GetUserId());

            var mail = user.Email.ToString();
            
            string _subject = "Đơn hàng từ Microwave Food đây :v";

            var mailInfo = new MailInfo { To = mail, Body = _body, Subject = _subject };
            SendMail(mailInfo);

            list = null;
            //Session["Cart"] = null;
            ListCart.Carts = null;
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            

            return View(order);
        }

        public void SendMail(MailInfo emailInfo)
        {
            string email = "microwavefood.https@gmail.com";
            string password = "Microwave123";
            using (MailMessage m = new MailMessage(email, emailInfo.To))
            {
                m.Subject = emailInfo.Subject;
                m.Body = emailInfo.Body;
                
                m.IsBodyHtml = false;
                using (SmtpClient smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    
                    NetworkCredential networkCred = new NetworkCredential(email, password);
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = networkCred;
                    smtp.Port = 587;
                    smtp.Send(m);
                    ViewBag.Message = "Sent";
                }
            }
        }

        public ActionResult History(int? type)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (user == null)
            {
                ViewBag.Message = "Vui lòng đăng nhập!";
                return View("Error");
            }
            List<Order> list = new List<Order>();
            if (type == null)
            {
                list = db.Orders.Include("Bills.Product").Where(a => a.Status == true && a.UserId == user.Id)
                    .OrderByDescending(a => a.OrderDate).ToList();
            }
            else if (type == 1) //1 = chưa giao
            {
                list = db.Orders.Include("Bills.Product").Where(a => a.Status == true && a.IsDelivered == false && a.UserId == user.Id)
                    .OrderByDescending(a => a.OrderDate).ToList();
            }
            else //còn lại = đã giao
            {
                list = db.Orders.Include("Bills.Product").Where(a => a.Status == true && a.IsDelivered == true && a.UserId == user.Id)
                    .OrderByDescending(a => a.OrderDate).ToList();
            }
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            return View(list);
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult OrderConfirm(int? type)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (user == null)
            {
                ViewBag.Message = "Vui lòng đăng nhập!";
                return View("Error");
            }
            List<Order> list = new List<Order>();
            if (type == null)
            {
                list = db.Orders.Include("Bills.Product").Include("User").Where(a => a.Status == true).OrderByDescending(a => a.OrderDate).ToList();
            }
            else if (type == 1) //1 = chưa giao
            {
                list = db.Orders.Include("Bills.Product").Include("User").Where(a => a.Status == true && a.IsDelivered == false).OrderByDescending(a => a.OrderDate).ToList();
            }
            else //còn lại = đã giao
            {
                list = db.Orders.Include("Bills.Product").Include("User").Where(a => a.Status == true && a.IsDelivered == true).OrderByDescending(a => a.OrderDate).ToList();
            }
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            return View(list);
        }

        public ActionResult Comment(int orderId)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (user == null)
            {
                ViewBag.Message = "Vui lòng đăng nhập!";
                return View("Error");
            }
            List<Bill> list = db.Bills.Include(a => a.Product).Include("comment").Where(a => a.OrderId == orderId).ToList();
            if (list == null)
            {
                ViewBag.Message = "Oops, something happened";
                return View("Error");
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult SendComment(int billId, string strUrl, string comment)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            if (user == null)
            {
                ViewBag.Message = "Vui lòng đăng nhập!";
                return View("Error");
            }
            var bill = db.Bills.Find(billId);
            if (bill == null)
            {
                ViewBag.Message = "Cannot find bill!";
                return View("Error");
            }
            Comment cmt = new Comment();
            cmt.CommentId = billId;
            cmt.BillId = billId;
            cmt.CommentDate = DateTime.Now;
            cmt.UserComment = comment;
            cmt.Status = true;
            cmt.UserId = user.Id;
            db.Comments.Add(cmt);
            db.SaveChanges();
            return Redirect(strUrl);
        }
        
        public ActionResult DeleteOrder(int orderId, string str)
        {
            var order = db.Orders.Find(orderId);
            if (order == null)
            {
                ViewBag.Message = "Cannot find order!";
                return View("Error");
            }
            order.Status = false;
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect(str);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Order/Comment.cshtml
@model IEnumerable<MicroWaveFood.Models.Bill>
@{
    ViewBag.Title = "Comment";
}

<h2>Comment</h2>

<div class="container">
    @foreach (var item in Model)
    {
        <form action="@Url.Action("SendComment", "Order", new { billId = item.BillId , strUrl = Request.Url.ToString()})" method="post">
            <div class="comment-wrapper shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                <div class="row">
                    <div class="col-sm-2">
                        <img class="img-detail-history" src="@item.Product.Image" />
                    </div>
                    <div class="col">
                        <p>@item.Product.ProductName</p>
                    </div>
                    <div class="col">
                        <textarea name="comment" class="form-control" rows="4" cols="50"></textarea>
                    </div>
                    <div class="col-sm-2">
                        @if (item.Comment == null)
                        {
                            <button type="submit" class="button-delivery-confirm mt-5">Gửi nhận xét</button>
                        }
                        else
                        {
                            <button type="submit" class="button-delivery-confirmed mt-5">Đã gửi nhận xét</button>
                        }

                    </div>
                </div>
            </div>
        </form>
    }

</div>

Views/Order/History.cshtml
@model IEnumerable<MicroWaveFood.Models.Order>
@{
    ViewBag.Title = "History";
}

<h2>Lịch sử mua hàng</h2>
<div class="container">
    <div class="history-wrapper">
        <div class="history-nav row shadow p-3 mb-5 bg-white rounded">
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("History", "Order")">Tất cả</a>
            </div>
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("History", "Order", new { type = 1})">Đang giao</a>
            </div>
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("History", "Order", new { type = 2})">Đã giao</a>
            </div>
        </div>
        <div class="history-detail">
            @foreach (var item in Model)
            {
                <div class="shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                    <div class="row">
                        @foreach (var subItem in item.Bills)
                        {
                            <div class="product-detail-history row col-10 ">
                                <div class="product-image-history">
                                    <img class="img-detail-history m-2" src="@subItem.Product.Image" />
                                </div>
                                <div class="product-info-history">
                                    <div class="product-name-history m-2">
                                        <a>@subItem.Product.ProductName</a>
                                    </div>
                                    <div class="product-amount-history m-2">
                                        <p>Số lượng: @subItem.Amount</p>
                                    </div>
                                </div>
                            </div>
                            <div class="product-price-history col">
                                <p>@(@subItem.Product.Price*@subItem.Amount) <span>đ</span></p>
                            </div>
                        }
                    </div>
                    <hr />
                    <div class="history-total-price my-3">
                        @if (item.IsDelivered == true)
                        {
                            <p class="text-success">Đã giao</p>
                        }
                        else
                        {
                            <p class="text-warning">Đang giao</p>
                            <a class="btn btn-info" href="@Url.Action("DeleteOrder","Order", new { orderId = item.OrderId, str = Request.Url.ToString()})">Hủy đơn hàng</a>
                        }

                        <p>Tổng tiền <span>@item.Total</span></p>
                    </div>
                    <div class="history-button">
                        @if (item.IsDelivered == true)
                        {
                            <form action="@Url.Action("Comment", "Order", new { orderId = item.OrderId })", method="post">
                                <button type="submit" class="button-comment-order">Đánh giá</button>
                            </form>
                        }
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Views/Order/OrderConfirm.cshtml
@model IEnumerable<MicroWaveFood.Models.Order>
@{
    ViewBag.Title = "History";
}

<h2>Lịch sử mua hàng</h2>
<div class="container">
    <div class="history-wrapper">
        <div class="history-nav row shadow p-3 mb-5 bg-white rounded">
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("OrderConfirm", "Order")">Tất cả</a>
            </div>
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("OrderConfirm", "Order", new { type = 1})">Đang giao</a>
            </div>
            <div class="col py-3 nav-item text-center">
                <a class="nav-link active" href="@Url.Action("OrderConfirm", "Order", new { type = 2})">Đã giao</a>
            </div>
        </div>
        <div class="history-detail">
            @foreach (var item in Model)
            {
                <div class="shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                    <p>Order ID: @item.OrderId - Buyer: @item.User.Email | Địa chỉ: @item.User.Province - @item.User.District - @item.User.Guild - @item.User.Address</p>
                    <hr />
                    <div class="row">
                        @foreach (var subItem in item.Bills)
                        {
                            <div class="product-detail-history row col-10 ">
                                <div class="product-image-history">
                                    <img class="img-detail-history m-2" src="@subItem.Product.Image" />
                                </div>
                                <div class="product-info-history">
                                    <div class="product-name-history m-2">
                                        <a>@subItem.Product.ProductName</a>
                                    </div>
                                    <div class="product-amount-history m-2">
                                        <p>Số lượng: @subItem.Amount</p>
                                    </div>
                                </div>
                            </div>
                            <div class="product-price-history col">
                                <p>@subItem.Product.Price <span>đ</span></p>
                            </div>
                        }
                    </div>
                    <hr />
                    <div class="history-total-price my-3">
                        @if (item.IsDelivered == true)
                        {
                            <p class="text-success">Đã giao</p>
                        }
                        else
                        {
                            <p class="text-warning">Đang giao</p>
                            <a class="btn btn-info" href="@Url.Action("DeleteOrder","Order", new { orderId = item.OrderId, str = Request.Url.ToString()})">Hủy đơn hàng</a>
                        }

                        <p>Tổng tiền <span>@item.Total</span></p>
                    </div>
                    <div class="history-button">
                        @if (item.IsDelivered != true)
                        {
                            <button class="button-delivery-confirm" value="@item.OrderId">Xác nhận đã giao</button>
                        }
                        else
                        {
                            <button class="button-delivery-confirmed">Đã xác nhận</button>
                        }
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('.button-delivery-confirm').on("click", function (e) {
                bootbox.confirm("Xác nhận đơn hàng đã giao?", function (result) {
                    if (result == true) {
                        var button = $(e.target);
                        $.post("/api/Order/OrderConfirm", { OrderId: button.val() })
                            .done(function () {
                                button.text("Đã xác nhận");
                                button.removeClass("button-delivery-confirm");
                                button.addClass("button-delivery-confirmed")
                            })
                    }
                })
            });
        })
    </script>
}

Views/Order/Payment.cshtml
@{

}

<div class="container">
    <h1>@ViewBag.Title</h1>
    <form>
        <div class="comment">
            <a href="@Url.Action("Index", "Home")" class="btn btn-primary">Trang chủ</a>
        </div>
    </form>
    <div class="py-xl-5 my-xl-5"></div>
    
</div>