Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class Sale
    {
        public int SaleId { get; set; }
        [Required]
        [Display(Name = "Tên mã giảm giá")]
        [StringLength(100, ErrorMessage = "Tên mã giảm giá không được quá 100 ký tự")]
        public string SaleName { get; set; }
        [Required]
        [Range(0, 100)]
        [Display(Name = "Phần trăm giảm giá (thang 100)")]
        public int SaleRate { get; set; }
        [Required]
        [ValidDate]
        [Display(Name = "Từ ngày")]
        public DateTime From { get; set; }
        [Required]
        [Display(Name = "Đến ngày")]
        public DateTime To { get; set; }
        [Required]
        [StringLength(1000, ErrorMessage = "Nội dung không quá 1000 ký tự")]
        [Display(Name = "Nội dung giảm giá")]
        public string SaleContent { get; set; }
        public virtual List<Product> Products { get; set; }
    }
}

ViewModels/SaleViewModel.cs
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MicroWaveFood.ViewModels
{
    public class SaleViewModel
    {
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public bool IsSelected { get; set; }
    }
}

Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MicroWaveFood.Models;
using MicroWaveFood.ViewModels;

namespace MicroWaveFood.Controllers
{
    [Authorize(Roles = "admin")]
    public class SalesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Sales
        public ActionResult Index()
        {
            return View(db.Sales.ToList());
        }

        [HttpPost]
        public ActionResult AddToSale(List<SaleViewModel> list, int saleId,string url)
        {

            //try
            //{
            //    var product = db.Products.Find(productId);
            //    var sale = db.Sales.Find(saleId);
            //    if (product == null || sale == null)
            //    {
            //        ViewBag.Message = "Error";
            //        return View("Error");
            //    }
            //    product.SaleId = sale.SaleId;
            //    db.Entry(product).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return Redirect(url);
            //}
            //catch (DbEntityValidationException e)
            //{
            //    foreach (var eve in e.EntityValidationErrors)
            //    {
            //        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
            //            eve.Entry.Entity.GetType().Name, eve.Entry.State);
            //        foreach (var ve in eve.ValidationErrors)
            //        {
            //            Debug.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
            //                ve.PropertyName, ve.ErrorMessage);
            //        }
            //    }
            //    throw;
            //}
            var sale = db.Sales.Find(saleId);
            if (sale == null)
            {
                ViewBag.Message = "Error";
                return View("Error");
            }

            foreach (var item in list)
            {
                var product = db.Products.Find(item.ProductId);
                if (product == null)
                {
                    return View("Error");
                }
                if (item.IsSelected == true)
                {
                    product.SaleId = saleId;
                }
                else
                {
                    product.SaleId = null;
                }
                db.Entry(product).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Details(List<SaleViewModel> list, int saleId, string url)
        {
            var sale = db.Sales.Find(saleId);
            if (sale == null)
            {
                ViewBag.Message = "Error";
                return View("Error");
            }

            foreach (var item in list)
            {
                var product = db.Products.Find(item.ProductId);
                if (product == null)
                {
                    ViewBag.Message = "Error";
                    return View("Error");
                }
                if (item.IsSelected == true)
                {
                    product.SaleId = saleId;
                }
                else
                {
                    product.SaleId = null;
                }
                db.Entry(product).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Sales/Details/5
        public ActionResult Details(int? id, int? productTypeId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Include("Products").FirstOrDefault(a => a.SaleId == id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            List<SaleViewModel> list = new List<SaleViewModel>();
            if (productTypeId == null)
            {
                foreach (var item in db.Products.Where(a => a.status == true).ToList())
                {
                    SaleViewModel saleView = new SaleViewModel
                    {
                        ProductId = item.ProductId,
                        ProductName = item.ProductName,
                        SaleId = (int)id,
                        IsSelected = item.SaleId == null ? false : true
                    };
                    list.Add(saleView);
                }
            }
            else
            {
                foreach (var item in db.Products.Where(a => a.status == true && a.ProductTypeId == productTypeId).ToList())
                {
                    SaleViewModel saleView = new SaleViewModel
                    {
                        ProductId = item.ProductId,
                        ProductName = item.ProductName,
                        SaleId = (int)id
                    };
                    list.Add(saleView);
                }
            }
            ViewBag.productTypeId = new SelectList(db.productTypes.Where(a => a.Status == true), "ProductTypeId", "Name");
           
            //SaleViewModel saleVM = new SaleViewModel
            //{
                
            //};
            return View(list);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SaleId,SaleName,SaleRate,From,To,SaleContent")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                if (sale.From > sale.To)
                {
                    ModelState.AddModelError("To", "From date must be smaller than To date");
                    return View(sale);
                }
                db.Sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sale);
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SaleId,SaleName,SaleRate,From,To,SaleContent")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sale);
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sale sale = db.Sales.FirstOrDefault(a => a.SaleId == id);
            foreach (var item in db.Products.Where(a => a.status == true && a.SaleId == id).ToList())
            {
                item.SaleId = null;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }

            db.Sales.Remove(sale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteSale(int productId, string url)
        {
            var product = db.Products.Find(productId);
            if (product == null)
            {
                ViewBag.Message = "Error";
                return View("Error");
            }
            product.SaleId = null;
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect(url);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Sales/Create.cshtml
@model MicroWaveFood.Models.Sale

@{
    ViewBag.Title = "Create";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 4 DatePicker</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SaleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="datepicker" name="From"/>
                <script>
                    $('#datepicker').datepicker({
                        uiLibrary: 'bootstrap4',
                        format: 'dd/mm/yyyy'
                    });
                </script>
                @*@Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="datepicker2" name="To" />
                <script>
                    $('#datepicker2').datepicker({
                        uiLibrary: 'bootstrap4',
                        format: 'dd/mm/yyyy'
                    });
                </script>
                @*@Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.SaleContent, new  { @class = "form-control", rows = 20, cols = 50, placeholder="Nội dung tối đa 255 kí tự" })
                @Html.ValidationMessageFor(model => model.SaleContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Sales/Delete.cshtml
@model MicroWaveFood.Models.Sale

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SaleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaleRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SaleContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleContent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Sales/Details.cshtml
@model List<MicroWaveFood.ViewModels.SaleViewModel>
@using MicroWaveFood.Models
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>

    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>
<div class="col-sm-7">
    @using (@Html.BeginForm())
    {
        <input type="hidden" name="url" value="@Request.Url.ToString()" />
        <input type="hidden" name="saleId" value="@Model[0].SaleId" />
        <div class="product row">
            @Html.DropDownList("productTypeId", null, htmlAttributes: new { @class = "form-control col producttype", @onchange = "changeFunction();", @saleId = Model[0].SaleId })
            <div class="col">
                <button class="btn btn-primary">Add sale off</button>
            </div>
        </div>
        <input name="url" value="@Request.Url.ToString()" type="hidden" />

        <div>
            <div>
                <h5 class="my-2">Danh sách sản phẩm đang được hưởng khuyến mãi này:</h5>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="row">
                        <h5 class="my-2 col-md-9">@Model[i].ProductName</h5>
                        @*<a class="my-2 col" href="@Url.Action("DeleteSale", "Sales", new { @productId = item.ProductId, @url = Request.Url.ToString()})">Delete</a>*@
                        @Html.CheckBoxFor(a => Model[i].IsSelected)
                        @Html.HiddenFor(a => Model[i].ProductId)
                    </div>
                }
            </div>
        </div>
    }
    @*<form action="/Sales/AddToSale" method="post">*@

    @*</form>*@
</div>

@section scripts
{
    <script>
        function changeFunction() {
            $productTypeid = $('.producttype').val();
            $id = $('.producttype').attr('saleId');
            window.location.href = "/Sales/Details/" + $id + "?productTypeId=" + $productTypeid;
        }
    </script>
}

Views/Sales/Edit.cshtml
@model MicroWaveFood.Models.Sale

@{
    ViewBag.Title = "Edit";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 4 DatePicker</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
</head>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SaleId)

        <div class="form-group">
            @Html.LabelFor(model => model.SaleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="datepicker" name="From" />
                <script>
                    $('#datepicker').datepicker({
                        uiLibrary: 'bootstrap4',
                        format: 'dd/mm/yyyy'
                    });
                </script>
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="datepicker2" name="To" />
                <script>
                    $('#datepicker2').datepicker({
                        uiLibrary: 'bootstrap4',
                        format: 'dd/mm/yyyy'
                    });
                </script>
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SaleContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Sales/Index.cshtml
@model IEnumerable<MicroWaveFood.Models.Sale>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SaleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SaleRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.To)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SaleContent)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SaleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SaleRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.To)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SaleContent)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SaleId }) |
            @Html.ActionLink("Details", "Details", new { id=item.SaleId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SaleId })
        </td>
    </tr>
}

</table>