Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class Product
    {
        [Key]
        [Column(Order = 1)]
        public int ProductId { get; set; }
        [Display(Name = "Tên loại sản phẩm")]
        public int ProductTypeId { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Tên không được quá 100 ký tự")]
        [Display(Name = "Tên sản phẩm")]
        public string ProductName { get; set; }
        [Required]
        [StringLength(1000, ErrorMessage = "Mô tả sản phẩm không được quá 1000 ký tự")]
        [Display(Name = "Mô tả sản phẩm")]
        public string ProductDescribe { get; set; }
        [Required]
        [Display(Name = "Gía sản phẩm")]
        [Range(1000, 100000000)]
        public long Price { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Đơn vị sản phẩm không được quá 50 ký tự")]
        public string Unit { get; set; }
        [Required]
        [ValidDate]
        [Display(Name = "Ngày nhập hàng")]
        public DateTime Date { get; set; }
        [Required]
        [Display(Name = "Hình ảnh")]
        public string Image { get; set; }
        [Required]
        [Range(1, 100000000)]
        public int Quantity { get; set; }
        [Required]
        public bool status { get; set; }
        [Required]
        [Display(Name = "Nguồn gốc xuất xứ")]
        [StringLength(50, ErrorMessage = "Nguồn gốc xuất xứ không được quá 50 ký tự")]
        public string Origin { get; set; }
        public ProductType ProductType { get; set; }

        public virtual List<Bill> Bills { get; set; }

        public int? SaleId { get; set; }
        public virtual Sale Sale { get; set; }
    }
}

Models/ProductType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MicroWaveFood.Models
{
    public class ProductType
    {
        [Key]
        [Column(Order = 1)]
        public int ProductTypeId { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Tên loại sản phẩm không được quá 100 ký tự")]
        [Display(Name = "Tên loại sản phẩm")]
        public string Name { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Tên nhóm loại sản phẩm không được quá 100 ký tự")]
        [Display(Name = "Nhóm loại sản phẩm")]
        public string GroupType { get; set; }
        [Required]
        [Display(Name = "Hình ảnh")]
        public string Image { get; set; }
        public bool Status { get; set; }
        public virtual List<Product> Products { get; set; }
    }
}

ViewModels/ProductViewModel.cs
using MicroWaveFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MicroWaveFood.ViewModels
{
    public class ProductViewModel
    {
        public Product Product { get; set; }
        public List<Product> RelatedProducts { get; set; }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using MicroWaveFood.Models;
using MicroWaveFood.ViewModels;
using PagedList;

namespace MicroWaveFood.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var products = db.Products.Where(a => a.status == true && a.ProductType.Status == true).Include(p => p.ProductType);
            return View(products.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            if (product.status == false)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.ProductTypeId = new SelectList(db.productTypes.Where(a => a.Status == true), "ProductTypeId", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductTypeId,ProductName,ProductDescribe,Price,Unit,Date,Image,Quantity,status,Origin")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.status = true;
                product.Image = "/Images/" + product.Image;
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductTypeId = new SelectList(db.productTypes, "ProductTypeId", "Name", product.ProductTypeId);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            if (product.status == false)
            {
                return HttpNotFound();
            }
            ViewBag.ProductTypeId = new SelectList(db.productTypes, "ProductTypeId", "Name", product.ProductTypeId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductTypeId,ProductName,ProductDescribe,Price,Unit,Date,Image,Quantity,Origin")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.status = true;
                product.Image = "/Images/" + product.Image;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductTypeId = new SelectList(db.productTypes, "ProductTypeId", "Name", product.ProductTypeId);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            if (product.status == false)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            product.status = false;
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [AllowAnonymous]
        public ActionResult ProductDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include(p => p.ProductType)
                .Include("Bills.Comment.User")
                .FirstOrDefault(p => p.ProductId == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            if (product.status == false)
            {
                return HttpNotFound();
            }
            ProductViewModel productViewModel = new ProductViewModel
            {
                Product = product,
                RelatedProducts = db.Products.Where(p => p.ProductTypeId == product.ProductTypeId && p.status == true).ToList()
            };
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            return View(productViewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        
        
        //==-----------'
        [AllowAnonymous]
        public ActionResult Search(string str)
        {
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            var products = db.Products
                .ToList()
                .Where(a => a.ProductName.ToLower().Contains(str.ToLower()) && a.status == true)
                .ToList();
            return View("ListProduct", products);
        }

        [AllowAnonymous]
        public ActionResult ListProduct(string str)
        {
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            var products = db.Products.Include("ProductType").ToList().Where(a => a.ProductType.GroupType.ToLower().Contains(str.ToLower()) && a.status == true).ToList();
            return View(products);
        }
        [AllowAnonymous]
        public ActionResult ListSale(string str)
        {
            var products = db.Products.Where(a => a.SaleId != null && a.status == true).ToList();
            return View(products);
        }
       

        public int AmountSum()
        {
            int amount = 0;
            //List<Cart> list = Session["Cart"] as List<Cart>;
            List<Cart> list = ListCart.Carts;
            if (list != null)
            {
                amount = list.Sum(n => n.Amount);
            }
            return amount;
        }

        public long PriceSum()
        {
            long sum = 0;
            //List<Cart> list = Session["Cart"] as List<Cart>;
            List<Cart> list = ListCart.Carts;
            if (list != null)
            {
                sum = list.Sum(n => n.Total);
            }
            return sum;
        }

        private static string ConvertToUnSign3(string s)
        {
            Regex regex = new Regex("\\p{IsCombiningDiacriticalMarks}+");
            string temp = s.Normalize(NormalizationForm.FormD);
            return regex.Replace(temp, String.Empty).Replace('\u0111', 'd').Replace('\u0110', 'D');
        }

        [AllowAnonymous]
        public ActionResult ProductsInProductType(int id)
        {
            ViewBag.AmountSum = AmountSum();
            ViewBag.PriceSum = PriceSum();
            var products = db.Products.Include("ProductType").Where(a => a.ProductType.ProductTypeId == id && a.status == true).ToList();
            return View("ListProduct", products);
        }
    }
}

Views/Products/Create.cshtml
@model MicroWaveFood.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductTypeId, "ProductTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescribe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ProductDescribe, new {  @class = "form-control" , cols = "20", rows = "20"} )
                @Html.ValidationMessageFor(model => model.ProductDescribe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" , type = "text"} })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, new { type = "file" })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" , type = "text"} })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/ListProduct.cshtml
@model IEnumerable<MicroWaveFood.Models.Product>
@{
    ViewBag.Title = "ListProduct";
}

<h4 class="title">
    Các Mặt hàng
</h4>
<div class="row">
    @if (Model.Count() == 0)
    {
        <h3 style="color:red; margin: auto">Không tìm thấy</h3>
    }
    @foreach (var item in Model)
    {
        <div class="col-md-3 pt-5">
            <div class="productImg" style="position:relative">
                @if (item.SaleId != null && item.Sale.From <= DateTime.Now && item.Sale.To >= DateTime.Now)
                {

                    <div class="sale">

                        <img src="~/Images/discount.png" />
                    </div>
                    <div class="discount">
                        <p style="text-align:right">- @item.Sale.SaleRate%</p>
                    </div>
                }
            <a href="@Url.Action("ProductDetail", "Products", new { id = item.ProductId})">
                <img class="img-index" src="@item.Image" />
            </a>
            </div>
            <div class="product-content-container">
                <div class="productContent">
                    <div>
                        <div class="product-content-container">
                            <div class="container text-center mt-1">
                                <a data-product-id="@item.ProductId" class="btn btn-primary button-index">Thêm vào giỏ hàng</a>
                            </div>
                            <div class="productContent">
                                <div class="product-name">
                                    <p style="text-align:center">@item.ProductName</p>
                                </div>
                                <div class="product-price">
                                    @if (item.SaleId != null && item.Sale.From <= DateTime.Now && item.Sale.To >= DateTime.Now)
                                    {
                                        <p style="text-align:center;"><del>@item.Price</del> <span style="color:red;">@(item.Price - (item.Price * item.Sale.SaleRate / 100)) đ</span></p>
                                    }
                                    else
                                    {
                                        <p style="text-align:center">@item.Price</p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>




@section scripts
{
    <script>
        $(document).ready(function () {
            $('.button-index').on("click", function (e) {
                var id = $(e.target);
                $.post("/api/Cart/Add", { productId: id.attr("data-product-id") })
                    .done(function () {
                        var value = parseInt($(".notify-number").text(), 10) + 1;
                        $('.notify-number').text(value);
                    })
                    .fail(function () {
                        bootbox.alert("Something is wrong!");
                    })
            })
        })
    </script>
}

Views/Products/ProductDetail.cshtml
@model MicroWaveFood.ViewModels.ProductViewModel

@{
    ViewBag.Title = "ProductDetail";
}
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<h2>Chi tiết sản phẩm</h2>
<!--Section: Block Content-->
<section class="mb-5">
    <div class="row">
        <div class="col-md-12 a-center">
            <a href="@Url.Action("Index","Home")">Trang Chủ</a>
            <i class="material-icons" style="font-size: medium">navigate_next</i>
            <a href="@Url.Action("ListProduct","Products", new {@str = @Model.Product.ProductType.GroupType })">@Model.Product.ProductType.GroupType</a>
            <i class="material-icons" style="font-size: medium">navigate_next</i>
            <a href="@Url.Action("ProductsInProductType","Products", new {@id = @Model.Product.ProductTypeId })">@Model.Product.ProductType.Name</a>
        </div>
        <div class="col-md-6 mb-4 mb-md-0">
            <div id="mdb-lightbox-ui">
                <a>
                    <img src="@Model.Product.Image" width="500" height="300"
                         class="img-fluid z-depth-1" />
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <h2>@Model.Product.ProductName</h2>
            <p class="mb-2 text-muted text-uppercase small" style="font-weight: lighter">@Model.Product.ProductType.Name</p>
            @if (Model.Product.SaleId != null && Model.Product.Sale.From <= DateTime.Now && Model.Product.Sale.To >= DateTime.Now)
            {
                <del><h6><span class="mr-1"><strong style="color: red; text-shadow: 2px 2px 3px #ccc; font-size: 25px; font-weight: bold;">@Model.Product.Price đ</strong></span></h6></del>
                <h6><span class="mr-1"><strong style="color: red; text-shadow: 2px 2px 3px #ccc; font-size: 25px; font-weight: bold;">@(@Model.Product.Price - Model.Product.Price * Model.Product.Sale.SaleRate / 100) đ</strong></span></h6>
            }
            else
            {
                <h6><span class="mr-1"><strong style="color: red; text-shadow: 2px 2px 3px #ccc; font-size: 25px; font-weight: bold;">@Model.Product.Price đ</strong></span></h6>
            }
            <p class="pt-1">
                @Model.Product.ProductDescribe
            </p>
            <hr />
            <div class="table-responsive mb-2">
                <table>
                    <tbody>
                        <tr>
                            <td class="pl-0 pb-0 w-25">Quantity</td>
                        </tr>
                        <tr>
                            <td class="pl-0">
                                <div class="def-number-input number-input safari_only mb-0 row">
                                    <div class="col-sm-2">
                                        <input class="changedInput" type="number" min="1" max="200" value="1" onchange="inputChanged();"/>
                                    </div>
                                    <div class="col">
                                        @if (Model.Product.SaleId != null && Model.Product.Sale.From <= DateTime.Now && Model.Product.Sale.To >= DateTime.Now)
                                        {
                                            <input type="hidden" id="hidden-price" value="@(@Model.Product.Price - Model.Product.Price * Model.Product.Sale.SaleRate / 100)" />
                                            <p style="color: red; text-shadow: 2px 2px 3px #ccc; font-size: 25px; font-weight: bold; padding-top: 0px;" id="price">@(@Model.Product.Price - Model.Product.Price * Model.Product.Sale.SaleRate / 100) đ</p>
                                        }
                                        else
                                        {
                                            <input type="hidden" id="hidden-price" value="@Model.Product.Price" />
                                            <p style="color: red; text-shadow: 2px 2px 3px #ccc; font-size: 25px; font-weight: bold; padding-top: 0px;" id="price">@Model.Product.Price</p>
                                        }
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <a class="btn btn-primary btn-md mr-1 mb-2 button-add-to-cart2" data-product-id="@Model.Product.ProductId">Mua hàng ngay</a>
            <button type="button" class="button-add-to-cart" style="background-color: orange; height: 35px;" data-product-id="@Model.Product.ProductId">
                <i class="fas fa-shopping-cart pr-2">Thêm vào giỏ hàng</i>
            </button>
        </div>
    </div>
    <div class="product-detail_content" style="padding-top: 20px;">
        <div class="_title" style=" border-bottom-style: double; border-bottom-color: blue; max-width: 900px">
            <h2>
                <i class="material-icons fa fa-comments-o">comment BÌNH LUẬN</i>
            </h2>
        </div>
        <div class="history-detail mt-3" style="max-width: 950px">
            @foreach (var item in Model.Product.Bills)
            {
                if (item.Comment != null)
                {
                    <div class="shadow p-3 mb-5 bg-white rounded" style="margin-left:-15px; margin-right:-15px;">
                        <div class="row">
                            <div class="product-detail-history row col-10 ">
                                <div class="user-icon">
                                    <img src="~/Images/user-icon.jpg" style="width:60px; height: 60px; border-radius: 30px;" />
                                </div>
                                <div class="product-info-history col">
                                    <div class="product-name-history m-2">
                                        <a>@item.Comment.User.Name</a>
                                    </div>
                                    <div class="product-name-history m-2">
                                        <a>@item.Comment.UserComment</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <h3 class="product-title">SẢN PHẨM LIÊN QUAN</h3>
    <div class="container">
        <div class="row">
            @foreach (var item in Model.RelatedProducts)
            {
                <div class="col pt-5">
                    <div class="productImg" style="position:relative">
                        @if (item.SaleId != null && item.Sale.From <= DateTime.Now && item.Sale.To >= DateTime.Now)
                        {

                            <div class="sale">

                                <img src="~/Images/discount.png" />
                            </div>
                            <div class="discount">
                                <p style="text-align:right">- @item.Sale.SaleRate%</p>
                            </div>
                        }
                        <a href="@Url.Action("ProductDetail", "Products", new { id = item.ProductId})">
                            <img class="img-index" src="@item.Image" />
                        </a>
                    </div>
                    <div class="product-content-container">
                        <div class="productContent">
                            <div>
                                <div class="product-content-container">
                                    <div class="container text-center mt-1">
                                        <a data-product-id="@item.ProductId" class="btn btn-primary button-index">Thêm vào giỏ hàng</a>
                                    </div>
                                    <div class="productContent">
                                        <div class="product-name">
                                            <p style="text-align:center">@item.ProductName</p>
                                        </div>
                                        <div class="product-price">
                                            @if (item.SaleId != null && item.Sale.From <= DateTime.Now && item.Sale.To >= DateTime.Now)
                                            {
                                                <p style="text-align:center;"><del>@item.Price</del> <span style="color:red;">@(item.Price - (item.Price * item.Sale.SaleRate / 100)) đ</span></p>
                                            }
                                            else
                                            {
                                                <p style="text-align:center">@item.Price</p>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</section>
@section scripts{
    <script>
        $(document).ready(function () {
            $('.button-add-to-cart').on("click", function (e) {
                var id = $(this);
                var a = $('.changedInput');
                if (parseInt(a.val(), 10) > 200) {
                    bootbox.alert("Bạn chỉ được chọn tối đa 200 sản phẩm này!");
                }
                else {
                    $.post("/api/AnotherCart", { productId: id.attr("data-product-id"), amount: a.val() })
                        .done(function () {
                            var value = parseInt($(".notify-number").text(), 10) + parseInt(a.val(), 10);
                            $('.notify-number').text(value);
                        })
                        .fail(function () {
                            bootbox.alert("Something is wrong!");
                        })
                }
            });
            $('.button-add-to-cart2').on("click", function (e) {
                var id = $(e.target);
                var amount = $('.changedInput').val();
                window.location.href = "/Cart/AddToCartWithAmount/?productId=" + id.attr("data-product-id") + "&amount=" + amount;
            })
        });
        function inputChanged() {
            var amount = $('.changedInput').val();
            var price = $('#hidden-price').val()
            $('#price').text(parseInt(amount, 10) * parseInt(price, 10) + "đ");
        }
    </script>
}